2025-07-29 10:00:08,194 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'users' already exists
  await self._query(query)
2025-07-29 10:00:08,245 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'userbots' already exists
  await self._query(query)
2025-07-29 10:00:08,296 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'commits' already exists
  await self._query(query)
2025-07-29 10:00:08,325 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'commit_votes' already exists
  await self._query(query)
2025-07-29 10:00:08,350 - ERROR - root - /usr/local/lib/python3.10/dist-packages/aiomysql/cursors.py:239: Warning: Table 'userbot_shared' already exists
  await self._query(query)
2025-07-29 10:01:23,451 - WARNING - aiogram.dispatcher - Received SIGINT signal
2025-07-29 10:01:23,703 - WARNING - root - Bot polling stopped. Shutting down...
